import { chromium } from 'playwright-core';
import fs from 'node:fs';
const SP = '/tmp/claude-0/-home-user-Playino/21106cdd-724f-594b-ad21-d623ecc271d7/scratchpad/';
const ID = process.env.ID || 'visor', NAME = process.env.NAME || '바이저로봇';
const D = SP + 'c3d/', TP = SP + 'three147/package/', OUT = SP + 'out2/' + ID + '/';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await b.newContext({ viewport: { width: 1200, height: 600 } });
await ctx.route('https://cdn.jsdelivr.net/npm/three@0.147.0/**', (r) => { const u = new URL(r.request().url()); r.fulfill({ body: fs.readFileSync(TP + u.pathname.replace('/npm/three@0.147.0/', ''), 'utf8'), contentType: 'text/javascript' }); });
const p = await ctx.newPage(); const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('file://' + D + 'render5.html');
for (const f of ['loaders/GLTFLoader.js', 'loaders/STLLoader.js', 'environments/RoomEnvironment.js']) await p.addScriptTag({ path: TP + 'examples/js/' + f });
const files = { glb: OUT + NAME + '_애니메이션.glb', lite: OUT + NAME + '_경량.glb', key: OUT + 'print/' + NAME + '_키링_40mm.stl', base: OUT + 'print/' + NAME + '_받침대일체_106mm.stl' };
const data = {}; for (const [k, f] of Object.entries(files)) data[k] = fs.readFileSync(f).toString('base64');
const info = await p.evaluate(async (data) => {
  const T = THREE; const ab = (s) => { const bin = atob(s), u = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) u[i] = bin.charCodeAt(i); return u.buffer; };
  document.body.innerHTML = '<canvas id="c" width="1200" height="600"></canvas>'; const cv = document.getElementById('c');
  const R = new T.WebGLRenderer({ canvas: cv, antialias: true, preserveDrawingBuffer: true }); R.setSize(1200, 600, false); R.outputEncoding = T.sRGBEncoding; R.setScissorTest(true); R.setClearColor(0xf2efe6);
  const env = new T.PMREMGenerator(R).fromScene(new T.RoomEnvironment(), 0.04).texture;
  const info = {};
  const view = (obj, i, up) => { const sc = new T.Scene(); sc.environment = env; sc.add(obj); sc.add(new T.DirectionalLight(0xffffff, 1.5)); obj.updateMatrixWorld(true); const bb = new T.Box3().setFromObject(obj), c = bb.getCenter(new T.Vector3()), h = bb.getSize(new T.Vector3()).length();
    const cam = new T.PerspectiveCamera(30, 300 / 600, 0.001, 1000); cam.position.set(c.x + h * 0.6, c.y + h * 0.25, c.z + h * 1.6); cam.lookAt(c); R.setViewport(i * 300, 0, 300, 600); R.setScissor(i * 300, 0, 300, 600); R.render(sc, cam); return bb; };
  const L = new T.GLTFLoader();
  const g1 = await new Promise((r, j) => L.parse(ab(data.glb), '', r, j)); info.anims = g1.animations.map((a) => a.name + ':' + a.duration.toFixed(1)); let sk = 0; g1.scene.traverse((o) => { if (o.isSkinnedMesh) sk++; }); info.skinned = sk;
  const mx = new T.AnimationMixer(g1.scene); mx.clipAction(g1.animations.find((a) => a.name === '환호')).play(); mx.update(0.2); view(g1.scene, 0);
  const g2 = await new Promise((r, j) => L.parse(ab(data.lite), '', r, j)); const mx2 = new T.AnimationMixer(g2.scene); mx2.clipAction(g2.animations.find((a) => a.name === '인사')).play(); mx2.update(0.5); view(g2.scene, 1);
  const SL = new T.STLLoader(); const mk = (s, col) => { const g = SL.parse(ab(s)); g.computeVertexNormals(); const m = new T.Mesh(g, new T.MeshStandardMaterial({ color: col, roughness: 0.6 })); m.rotation.x = -Math.PI / 2; const o = new T.Group(); o.add(m); g.computeBoundingBox(); return [o, g.boundingBox]; };
  const [k, kb] = mk(data.key, 0xd9d4ca); view(k, 2); info.key = [kb.min.toArray().map((v) => +v.toFixed(1)), kb.max.toArray().map((v) => +v.toFixed(1))];
  const [bs, bb] = mk(data.base, 0xd9d4ca); view(bs, 3); info.base = [bb.min.toArray().map((v) => +v.toFixed(1)), bb.max.toArray().map((v) => +v.toFixed(1))];
  return info;
}, data);
await p.addScriptTag({ path: TP + 'examples/js/environments/RoomEnvironment.js' }).catch(() => {});
console.log(JSON.stringify(info), errs);
await (await p.$('#c')).screenshot({ path: SP + 'c3d/_verify2.png' }); await b.close();
